# PyTorch Fundamentals & Tensor Operations
Welcome to the **PyTorch Fundamentals** tutorial. This notebook serves as an interactive reference guide covering all essential tensor manipulation operations required for deep learning research and development.

### Key Concepts Covered:
1. **Tensor Shapes & Inspection**: Dimension, rank, and size metrics.
2. **Data Types**: Float, Int, Double, Long, and casting methods.
3. **Tensor Math**: Basic addition, subtraction, division, and scaling.
4. **Matrix Multiplication**: Inner products, dot products, and shape constraints.
5. **In-place Operations**: Modifying tensors in-memory without extra allocation.
6. **GPU Acceleration**: CUDA integration and device allocation.
7. **Reshaping**: View, reshape, transpose, and squeeze utilities.
8. **NumPy Integration**: Sharing underlying memory buffers between PyTorch and NumPy.


In [3]:
# Check if CUDA-capable GPU is available on this system
if torch.cuda.is_available():
    print("Gpu is available")
    print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available . using Cpu")

Gpu is available
using GPU: NVIDIA GeForce RTX 4050 Laptop GPU


In [4]:
#create a tensor

In [6]:
#empty tensor
a = torch.empty(2,3)

In [9]:
#check type
type(a)

torch.Tensor

In [10]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [15]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
#using random
torch.rand(2,3)

tensor([[0.7375, 0.4855, 0.6211],
        [0.7176, 0.5495, 0.9136]])

In [21]:
#seed --> Reproduse constant value by rand function
torch.manual_seed(1)
torch.rand(2,3)

tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])

In [23]:
#making custom value 
torch.tensor([[1,2],[3,4]])

tensor([[1, 2],
        [3, 4]])

In [25]:
#other Way 

#arange function
print("using arang --> \n", torch.arange(0,10,2))

using arang --> 
 tensor([0, 2, 4, 6, 8])


In [26]:
#using linspace
print("using linspace --> \n", torch.linspace(0,10,10))

using linspace --> 
 tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [29]:
#using eye
print("using eye --> \n", torch.eye(3))

using eye --> 
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [31]:
#using full 
print("using full --> \n", torch.full((2,2),5))

using full --> 
 tensor([[5, 5],
        [5, 5]])


## 1. Tensor Shapes and Dimensions
Tensors are multi-dimensional arrays with a uniform type (dtype). Here we inspect properties like shape, dimension ranks, and length parameters.


In [36]:
# Initialize a PyTorch tensor
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [38]:
x.shape

torch.Size([2, 3])

In [39]:
#copying Tensor shape
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [41]:
#copying Tensor shape and making 0 tensor
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [42]:
#copying Tensor shape and making 1's tensor
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [48]:
#copying Tensor shape and making random value tensor
torch.rand_like(x, dtype = torch.float64)

tensor([[0.4609, 0.7084, 0.5798],
        [0.4967, 0.5104, 0.3295]], dtype=torch.float64)

## 2. Tensor Data Types
PyTorch supports various numeric types (Float32, Float64, Int64, etc.). Maintaining correct dtypes is crucial to prevent type mismatch errors during backpropagation.


In [43]:
#find data type
x.dtype

torch.int64

In [45]:
#assign data type
torch.tensor([1,2,3], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [46]:
#using to ()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## 3. Basic Mathematical Operations
We perform standard arithmetic operations (addition, subtraction, division, multiplication) on tensors.


1. Scaler operation

In [49]:
x = torch.rand(2,2)
x

tensor([[0.3398, 0.5239],
        [0.7981, 0.7718]])

In [50]:
#addition 
x +2

tensor([[2.3398, 2.5239],
        [2.7981, 2.7718]])

In [52]:
#subtraction 
x -2

tensor([[-1.6602, -1.4761],
        [-1.2019, -1.2282]])

In [53]:
#multiplcation
x*2

tensor([[0.6796, 1.0479],
        [1.5961, 1.5435]])

In [54]:
#division
x/2

tensor([[0.1699, 0.2620],
        [0.3990, 0.3859]])

In [56]:
#INT DIVISION
(x*100)//3

tensor([[11., 17.],
        [26., 25.]])

In [55]:
#MOD 
((x * 100)//3)%2

tensor([[1., 1.],
        [0., 1.]])

In [57]:
#power 
x**2

tensor([[0.1154, 0.2745],
        [0.6369, 0.5956]])

## 4. Element-wise Operations
Element-wise operations apply transformations on each individual coordinate independently.


In [58]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.0112, 0.8100, 0.6397],
        [0.9743, 0.8300, 0.0444]])
tensor([[0.0246, 0.2588, 0.9391],
        [0.4167, 0.7140, 0.2676]])


In [59]:
#Add
a+b

tensor([[0.0358, 1.0688, 1.5787],
        [1.3910, 1.5440, 0.3121]])

In [60]:
#sub
a-b

tensor([[-0.0134,  0.5511, -0.2994],
        [ 0.5576,  0.1161, -0.2232]])

In [61]:
#multiply
a*b

tensor([[2.7608e-04, 2.0965e-01, 6.0070e-01],
        [4.0600e-01, 5.9262e-01, 1.1892e-02]])

In [62]:
#division
a/b

tensor([[0.4564, 3.1293, 0.6812],
        [2.3380, 1.1625, 0.1660]])

In [63]:
#power
a**b

tensor([[0.8955, 0.9469, 0.6573],
        [0.9892, 0.8755, 0.4346]])

In [64]:
#Mod
a%b

tensor([[0.0112, 0.0335, 0.6397],
        [0.1408, 0.1161, 0.0444]])

In [65]:
# Initialize a PyTorch tensor
c = torch.tensor([1,2,3])

In [67]:
#abs --> absolute
torch.abs(c)

tensor([1, 2, 3])

In [68]:
#negative
torch.neg(c)

tensor([-1, -2, -3])

In [69]:
# Initialize a PyTorch tensor
d = torch.tensor([1.1, 2.2, 3.4, 4.5])

In [70]:
# round
torch.round(d)

tensor([1., 2., 3., 4.])

In [71]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [72]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [73]:
#clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.2000, 3.0000, 3.0000])

## 5. Reduction Operations
Reduction operations compress multi-dimensional arrays into lower-order summaries (like sum, mean, minimum, maximum, and index locations).


In [84]:
e = torch.randint(size=(2,3), low=0, high=10, dtype =float)
e

tensor([[7., 8., 6.],
        [9., 9., 8.]], dtype=torch.float64)

In [78]:
#sum of tensor
torch.sum(e)

tensor(17)

In [81]:
#sum along columns
torch.sum(e, dim=0)

tensor([11,  1,  5])

In [82]:
#sum along rows
torch.sum(e, dim=1)

tensor([9, 8])

In [85]:
#mean
torch.mean(e)

tensor(7.8333, dtype=torch.float64)

In [86]:
#mean along col
torch.mean(e, dim =0)

tensor([8.0000, 8.5000, 7.0000], dtype=torch.float64)

In [87]:
#median
torch.median(e)

tensor(8., dtype=torch.float64)

In [88]:
#max
torch.max(e)

tensor(9., dtype=torch.float64)

In [89]:
#min
torch.min(e)

tensor(6., dtype=torch.float64)

In [91]:
#PRODUCT
torch.prod(e)

tensor(217728., dtype=torch.float64)

In [92]:
#standard deviation
torch.std(e)

tensor(1.1690, dtype=torch.float64)

In [93]:
#varience
torch.var(e)

tensor(1.3667, dtype=torch.float64)

In [ ]:
#argmax --> give position of max value
torch.argmax(e)

tensor(3)

In [ ]:
#argmin -> give position of min value
torch.argmin(e)  

tensor(2)

## 6. Matrix Multiplication
Matrix multiplication is the fundamental build block of linear layer transformations. In PyTorch, this is computed using `torch.matmul` or the `@` operator.


In [98]:
f = torch.randint(size =(2,3), low =0, high =10)
g = torch.randint(size =(3,2), low =0, high =10)

print(f)
print(g)

tensor([[3, 3, 1],
        [7, 2, 8]])
tensor([[9, 3],
        [0, 2],
        [2, 8]])


In [100]:
#Matrix multiplication
torch.matmul(f,g)

tensor([[29, 23],
        [79, 89]])

In [101]:
# Initialize a PyTorch tensor
vect1 = torch.tensor([1,2])
vect2 = torch.tensor([3,4])

In [102]:
#dot prodcut
torch.dot(vect1,vect2)

tensor(11)

In [104]:
#transpose
torch.transpose(f,0,1)

tensor([[3, 7],
        [3, 2],
        [1, 8]])

In [110]:
h = torch.randint(size =(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[6., 9., 0.],
        [8., 7., 7.],
        [3., 2., 7.]])

In [111]:
#determinat
torch.det(h)

tensor(-105.0000)

In [112]:
#inverse
torch.inverse(h)

tensor([[-0.3333,  0.6000, -0.6000],
        [ 0.3333, -0.4000,  0.4000],
        [ 0.0476, -0.1429,  0.2857]])

## 7. Comparison Operations
Boolean operators evaluate inequality relations coordinate-wise across tensor inputs.


In [113]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 2, 7],
        [3, 3, 3]])
tensor([[6, 6, 6],
        [0, 0, 7]])


In [114]:
#greater than 
i>j

tensor([[ True, False,  True],
        [ True,  True, False]])

In [115]:
#less than
i<j

tensor([[False,  True, False],
        [False, False,  True]])

In [116]:
#equal to 
i==j

tensor([[False, False, False],
        [False, False, False]])

In [117]:
#not equal to 
i != j

tensor([[True, True, True],
        [True, True, True]])

## 8. Special Initialization Functions
PyTorch offers various standard array initializers (e.g., identity matrices, random uniform/normal configurations, constants).


In [131]:
k = torch.randint(size=(2,3), low =0, high=10,dtype=torch.float32)
k

tensor([[1., 9., 7.],
        [9., 9., 3.]])

In [120]:
#log 
torch.log(k)

tensor([[0.6931,   -inf,   -inf],
        [2.0794,   -inf, 0.6931]])

In [121]:
#exp
torch.exp(k)

tensor([[7.3891e+00, 1.0000e+00, 1.0000e+00],
        [2.9810e+03, 1.0000e+00, 7.3891e+00]])

In [123]:
#sqrt
torch.sqrt(k)

tensor([[1.4142, 0.0000, 0.0000],
        [2.8284, 0.0000, 1.4142]])

In [124]:
#sqrt
torch.sqrt(k)

tensor([[1.4142, 0.0000, 0.0000],
        [2.8284, 0.0000, 1.4142]])

In [125]:
#sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.5000, 0.5000],
        [0.9997, 0.5000, 0.8808]])

In [132]:
#softmax - > only work on float 
torch.softmax(k, dim=0)

tensor([[3.3535e-04, 5.0000e-01, 9.8201e-01],
        [9.9966e-01, 5.0000e-01, 1.7986e-02]])

In [133]:
#relu
torch.relu(k)

tensor([[1., 9., 7.],
        [9., 9., 3.]])

## 9. In-place Operations
Operators postfixed with an underscore (e.g., `add_()`, `sub_()`) modify the tensor's contents directly inside its current memory address.


In [134]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.3937, 0.7881, 0.9642],
        [0.1895, 0.6085, 0.9314]])
tensor([[0.8313, 0.8116, 0.8553],
        [0.8163, 0.6291, 0.1581]])


In [136]:
# to store addition on same variable
# ( - )
m + n  # it store sum in new tensor 

tensor([[1.2251, 1.5997, 1.8195],
        [1.0057, 1.2377, 1.0895]])

In [138]:
m.add_(n) # it store value in m tensor

tensor([[2.0564, 2.4113, 2.6748],
        [1.8220, 1.8668, 1.2476]])

In [140]:
torch.relu(m) # it stor value in new tensor

tensor([[2.0564, 2.4113, 2.6748],
        [1.8220, 1.8668, 1.2476]])

In [142]:
m.relu_() # it store value in m tensor

tensor([[2.0564, 2.4113, 2.6748],
        [1.8220, 1.8668, 1.2476]])

## 10. Cloning and Copying Tensors
We contrast shallow pointer assignments with deep memory allocations (`clone()`) to prevent unintended side effects.


In [149]:
a = torch.rand(2,3)
a

tensor([[0.9885, 0.4422, 0.4828],
        [0.0281, 0.1782, 0.2079]])

In [150]:
b = a # it copy the tensor a on b but it have some problem

In [151]:
b 

tensor([[0.9885, 0.4422, 0.4828],
        [0.0281, 0.1782, 0.2079]])

In [ ]:
b[0][0] = 0 # it also chnage the value in a tensor 

In [153]:
b

tensor([[0.0000, 0.4422, 0.4828],
        [0.0281, 0.1782, 0.2079]])

In [ ]:
a 

tensor([[0.0000, 0.4422, 0.4828],
        [0.0281, 0.1782, 0.2079]])

In [155]:
# CHECKIG THE VALUE OF TENSOR STORE IN MEMORY 
id(a)

1890038114368

In [156]:
id(b)

1890038114368

In [ ]:
# to clone the tensor in different variable
b =a.clone()

In [158]:
a[0][0] = 10

In [159]:
a

tensor([[10.0000,  0.4422,  0.4828],
        [ 0.0281,  0.1782,  0.2079]])

In [160]:
b

tensor([[0.0000, 0.4422, 0.4828],
        [0.0281, 0.1782, 0.2079]])

In [161]:
id(a)

1890038114368

In [162]:
id(b)

1890037613968

## 11. CUDA & GPU Acceleration
We query the local hardware acceleration environment and transfer variables onto the graphic processor units (GPUs) for faster computation.


In [165]:
# Check if CUDA-capable GPU is available on this system
torch.cuda.is_available()

True

In [166]:
device = torch.device('cuda')

In [167]:
#creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.8903, 0.0275, 0.9031],
        [0.5386, 0.7312, 0.9047]], device='cuda:0')

In [169]:
#moving an exiating tensor to GPU

a = torch.rand(2,3)
a

tensor([[0.8238, 0.2413, 0.6084],
        [0.3180, 0.3877, 0.1015]])

In [ ]:
b = a.to(device) #moved in GPU

## 12. Reshaping and Dimensionality Manipulation
We alter layout mappings of dimensions using contiguous (`view`, `reshape`) and transpose methods.


In [172]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [179]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [180]:
#flattern
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [182]:
b = torch.rand(2,3,4)
b

tensor([[[0.5283, 0.8619, 0.1483, 0.7348],
         [0.8212, 0.9891, 0.1500, 0.6211],
         [0.1303, 0.9269, 0.3060, 0.8012]],

        [[0.5149, 0.4611, 0.4840, 0.5850],
         [0.7357, 0.5802, 0.6525, 0.0502],
         [0.8643, 0.9359, 0.9133, 0.8696]]])

In [183]:
# permute
b.permute(2,0,1)

tensor([[[0.5283, 0.8212, 0.1303],
         [0.5149, 0.7357, 0.8643]],

        [[0.8619, 0.9891, 0.9269],
         [0.4611, 0.5802, 0.9359]],

        [[0.1483, 0.1500, 0.3060],
         [0.4840, 0.6525, 0.9133]],

        [[0.7348, 0.6211, 0.8012],
         [0.5850, 0.0502, 0.8696]]])

In [184]:
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [185]:
#unsqueeze
c = torch.rand(226, 226,3) #image size

In [187]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [190]:
#squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## 13. Interoperability with NumPy
PyTorch tensors share the same underlying memory buffer as NumPy arrays when converted, allowing zero-copy operations.


In [191]:
import numpy as np

In [192]:
# Initialize a PyTorch tensor
a = torch.tensor([1,2,3])

In [197]:
b=a.numpy() # convert tensor to numpy array 

In [198]:
type(b)

numpy.ndarray

In [199]:
c = np.array([1,2,3])

In [201]:
torch.from_numpy(c)  #numpy array to tensor 

tensor([1, 2, 3])