# Building Neural Network Models in PyTorch
This notebook covers the fundamentals of creating and visualizing Neural Network models using PyTorch's `nn.Module`. We will learn how to:
1. Define a simple Logistic Regression model (Single Layer Neural Network).
2. Inspect model weights, biases, and parameters.
3. Visualize model architecture using the `torchinfo` library.
4. Define a Multi-Layer Perceptron (MLP) with hidden layers.

## 1. Importing Required Libraries
First, we import the core PyTorch library along with the neural network module `torch.nn` (typically imported as `nn`).

In [1]:
# Required Libraries
import torch
import torch.nn as nn

## 2. Creating a Model without Hidden Layers
We define a custom class `Model` that inherits from `nn.Module`. 
- In `__init__`, we define our layers (a linear mapping `nn.Linear` and a `nn.Sigmoid` activation).
- In `forward`, we define the forward computation path.

In [2]:
# Creating Model without Hidden Layer 
class Model(nn.Module):
    def __init__(self, num_features): # constructor
        super().__init__()
        # nn.Linear performs: out = features * weights^T + bias
        self.linear = nn.Linear(in_features=num_features, out_features=1)
        # Sigmoid activation to squash outputs between 0 and 1
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        # Define the forward pass pipeline
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

## 3. Instantiating the Model & Forward Pass
We generate dummy input data (features) using `torch.rand` and pass it through the model to obtain predictions.

In [3]:
# Create dummy dataset with 10 samples and 5 features
features = torch.rand(10, 5)

# Instantiate model
model = Model(num_features=features.shape[1])

# Call model for forward pass (automatically invokes the forward() method)
predictions = model(features)
print("Predictions Shape:", predictions.shape)
print("Predictions:\n", predictions)

Predictions Shape: torch.Size([10, 1])
Predictions:
 tensor([[0.5122],
        [0.4603],
        [0.5378],
        [0.5071],
        [0.5009],
        [0.5353],
        [0.4623],
        [0.5448],
        [0.5566],
        [0.5616]], grad_fn=<SigmoidBackward0>)


## 4. Inspecting Model Parameters
We can access the automatically initialized weight matrix and bias vector of the linear layer.

In [4]:
# Show model weights (automatically initialized)
print("Weights:\n", model.linear.weight)

Weights:
 Parameter containing:
tensor([[ 0.2846, -0.3529,  0.4361, -0.4129,  0.1718]], requires_grad=True)


In [5]:
# Show model biases
print("Bias:\n", model.linear.bias)

Bias:
 Parameter containing:
tensor([0.0276], requires_grad=True)


## 5. Visualizing Model Architecture using `torchinfo`
We install and use `torchinfo` to print a beautiful, detailed summary of our neural network parameters and shapes.

In [6]:
# Install torchinfo if not already installed
# !pip install torchinfo

In [7]:
# Visualize model summary
from torchinfo import summary 

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

## 6. Creating a Model with Hidden Layers
Now let's build a deeper network (Multi-Layer Perceptron) with a hidden layer. 
We will define a model with `num_features` input nodes, a hidden layer with 3 nodes, and a single output node.

In [8]:
# Creating Model with Hidden Layer 
class ModelWithHiddenLayer(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        
        # Defining layers individually for clarity
        self.linear1 = nn.Linear(num_features, 3)  # Input layer to hidden layer
        self.relu = nn.ReLU()                     # Activation function for hidden layer
        self.linear2 = nn.Linear(3, 1)            # Hidden layer to output layer
        self.sigmoid = nn.Sigmoid()               # Output activation

    def forward(self, features):
        # Pass inputs sequentially through layers
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

## 7. Visualizing the Deep Model
We instantiate our MLP model and display its structural summary.

In [9]:
# Instantiate MLP
mlp_model = ModelWithHiddenLayer(num_features=features.shape[1])

# Visualize the MLP model summary
summary(mlp_model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
ModelWithHiddenLayer                     [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00